version: '2'
services:
    bookingsapp-app:
        image: bookingsapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bookingsapp-postgresql:5432/BookingsApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bookingsapp-postgresql:
        extends:
            file: postgresql.yml
            service: bookingsapp-postgresql
